apiVersion: v1
kind: Pod
metadata:
  name: fortune3s
spec:
  containers:
  - image: luksa/fortune:args
    env:
      - name: INTERVAL
        value: "30"
      - name: MYARG
        value: hehe
      - name: THIRDARG
        value: "$(MYARG)haha"
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}